---
title: |
  | Learning can mediate both badges of status and individual recognition
author:
- Andrés E. Quiñones^[Laboratorio de Biología Evolutiva de Vertebrados, Departamento
  de Ciencias Biológicas, Universidad de los Andes, Bogotá, Colombia]
- C. Daniel Cadena*
- Olof Leimar^[Department of Zoology, Stockholm University, Stockholm, Sweden]
- Redouan Bshary^[Institute of Biology, University of Neuchâtel, Neuchâtel, Switzerland]
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document: default
  word_document: default
fig_caption: yes
fontsize: 12pt
header-includes:
- \usepackage{float}
- \usepackage{setspace}\doublespacing
- \linespread{2}
- \usepackage{lineno}
- \linenumbers
keep_tex: yes
keywords: My keywords
linespread: 2
bibliography: ../SocialMorphCue.bib
spacing: double
style: C:\Users\andre\Zotero\styles\elife.csl
abstract: Adaptive behavioural responses often depend on qualities of the interacting partner of an individual. For example, when competing for resources, an individual might be better off escalating fights with individuals of lower quality, while restraining from fighting individuals of higher quality. Communication systems involving signals of quality allow individuals to reduce uncertainty regarding the fighting ability of their partners and make more adaptive behavioral decisions. However, dishonest individuals can destabilize such communications systems. One open question is whether cognitive mechanisms, such as learning, can maintain the honesty of signals, thus, favoring their evolutionary stability. Here we present evolutionary simulations, where individuals can produce a signal proportional to their quality; and learn along their lifetime the best response to the signal emitted by their peers. In these simulations, learning on the receiver side can mediate the evolution of signals of quality on the sender side. When the cost of the signal is proportional to the quality of the sender populations are only composed of honest signalers. When the cost is not proportional to the quality of the signaler, the population is composed of both honest and dishonest signalers. We argue that learning can be a general cognitive mechanism playing a role in a wide range of communication systems.  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction 

The outcome of interactions with con-specifics is an important 
determinant of fitness in social animals. Irrespective of whether such interactions are cooperative 
or competitive, the actions of interacting individual partly determine 
their reproductive success. However, the best action for an individual 
might vary depending on its condition, and that of individuals with whom it interacts. 
Thus, acting based on information about interacting 
partners is typically adaptive [@quinones_Negotiation_2016].
Acquiring this information, however, is far from trivial. 
In some cases, interacting partners (signalers) might be 'willing' to provide accurate
information, but in others it might be in their own interest to conceal information
[@johnstone_Recognition_1997], or to provide erroneous information [@johnstone_Badges_1993]. 
Typically, in a given context, some proportion of individuals will beenefit 
from broadcasting accurate information, whereas others will benefit from hiding it. 
Take, for instance, an interaction between two individuals where one can help the other. 
Given some costs and benefits, a potential donor will be interested in helping 
related individuals. Therefore, for a relative of the donor, 
broadcasting kinship is advantageous, whereas for an unrelated individual, 
concealing the lack of kinship is better. Similar scenarios may apply to 
many aspects of social life such as finding mates, feeding offspring, dominance relationships 
and aggressive interactions [@bradbury_Principles_2011; @moller_Female_1988; @tibbetts_Socially_2004].
In dominance and aggressive interactions, an important piece of
information to guide individual actions is interacting partners fighting ability, 
which is sometimes referred to as Resource Holding Potential (RHP) [@parker_Assessment_1974], 
or simply as quality. Responsiveness to the quality of the 
partner is central to communication systems such as badges of status, 
where an arbitrary signal conveys quality [@johnstone_Badges_1993; @rohwer_Social_1975a]. 
Here, arbitrary refers to a signal which is not ontogenetically correlated with quality. 
Badges of status can be evolutionarily stable whenever the signal imposes a fitness cost which 
decreases with the quality of an individual  [@botero_Evolution_2010; @johnstone_Badges_1993], 
such that it's no longer in the interest of low quality individuals to fake quality by producing a
large badge. The cost of honest signals is a more general principle of communications systems, 
usually referred to as the handicap principle [@grafen_Biological_1990; @zahavi_Mate_1975]. 
An alternative system of communication is one where individuals gather and store information
about each individual they interact with. This information should reliably allow 
each individual to react adaptively to the quality difference with their opponent. 
This type of assessment strategy is often referred to as individual recognition [@whitfield_Plumage_1986]. Evidently, individual recognition is restricted to 
certain interaction structures, because individuals are limited by cognitive 
abilities in how many individuals they can recognize and track. Thus, individual 
recognition and badges of status have been assumed to be alternative communication 
systems fulfilling the same function, reducing the costs of aggression in contests over resources. 
Furthermore, badges of status and individual recognition are expected to evolve under different interaction structures, badges of status under global interactions and individual recognition
under local interactions [@dale_Signaling_2001; @sheehan_There_2016].  There is no clear cut reason, however, why both systems could not work together, in fact there is some evidence
that they can [@chaine_Manipulating_2018].

A somewhat ignored component of communication systems, in the context of aggressive 
interactions, is the cognitive aspects of the receiver module. Communication systems
relying on badges of status are often assumed to be cognitively less demanding 
than those involving individual recognition [@sheehan_There_2016] because in the latter, 
individuals need to store identity and associated information about each individual 
they interact with. In contrast, the response towards badges of status is often 
thought to be innate [@botero_Evolution_2010; @johnstone_Badges_1993], with 
individuals using their own quality and the opponent's badge to determine whether to aggressively
engage in contest. An alternative view of badges of status is that individuals learn 
to react to them based on their experiences [@guilford_Receiver_1991], which would imply that receivers must learn to associate signals with the fighting ability of bearers just as in systems based on individual recognition. In cases where badges of status vary quantitatively (e.g. in size or intensity), fighting ability may increase monotonically with attributes of the badge and would be reinforced by every interaction, so in principle learning would be faster than in systems involving individual recognition in which the association between signals and their meaning would vary depending on the interacting partners. In any case, learning could be a central cognitive mechanism in both types of communication systems, but the role of learning in these contexts has not been thoroughly explored in the empirical nor theoretical literature. 

Associative learning is a key cognitive mechanism that allows individuals to associate
rewards with environmental stimuli and thus behave adaptively [@staddon_Adaptive_2016]. 
Associative learning exists in all major vertebrate taxa, and in many invertebrates [@heyes_Simple_2012;@macphail_Brain_1982; @staddon_Adaptive_2016; @behrens_Associative_2008].
Theory has shown that natural selection favors these associations in complex environments
where conditions are hard to predict [@dridi_Environmental_2016]. Besides its wide taxonomic and
ecological relevance, associative learning is a flexible cognitive mechanism whose underpinings
show interspecific variation [@enquist_Power_2016; @quinones_Reinforcement_2019], so 
presumably, it has been modified by natural selection. Despite all this, associative 
learning is not often included in the narrative of evolutionary explanations of 
behavioural patterns [@fawcett_Exposing_2013; @kamil_Optimal_1983; @mcauliffe_Psychology_2015]. 
Computational models of evolution can play an important role to overcome the 
lack of integration between learning and evolution. Reinforcement learning theory 
encompases a series of computational methods inspired on the psychological and 
neurological mechanisms of associative learning [@sutton_Reinforcement_2018].
These set of algorithms allow the implementation of biologically realistic problems, 
capturing the essence of learning processes [@frankenhuis_Enriching_2018; @quinones_Reinforcement_2019]. 
Furthermore, these algorithms can be embedded in evolutionary simulations to 
generate theoretical predictions of the effect that learning can have in behavioral
evolution [@leimar_Learning_2019].

In here we present an evolutionary model where individuals use associative learning 
to develop a tendency to behave aggressively (or  peacefully), in the context of
competition over resources, depending on the quantitative morphological trait 
they perceive in their opponent (badge). Over evolutionary time individuals evolve
the size of their badge, and whether it depends on their quality. Under this simple
set up, individuals can use the badge both as a signal of quality (BS)
or as a trait for IR. We use the model to assess under what conditions of interaction
structure we expect different communication signals to evolve. 

## The model

We model the evolution of signals of quality in the context of agonistic interactions by 
modelling a population of haploid individuals with non-overlaping generations. 
Individuals are born every generation with a level of quality ($Q_i$, where $i$ is subscript 
of the population vector of size $N$) given by a number between zero and one, which is drawn 
from a truncated normal distribution $N(\mu = 0.5,\sigma)$. 
An Individual with quality $0$ has the lowest RHP, 
while an individual with quality $1$ has the highest. As part of development processes
individuals produce a morphological signal (badge), the size of such depends on their level 
of quality according to a reaction norm given by $B_i=1/(1+e^{\alpha_i-\beta_i Q_i})$;
where are $\alpha_i$ and $\beta_i$ are individual specific traits that determine 
the shape of the reaction norm. Variation in $\alpha_i$ and $beta_i$ means individuals
can have either uninformative (flat) or informative (logistic) norms; but the size of 
the signal is constrained between zero and one. We assume different values of these traits 
are given by different alleles, and are inherited from mother to offspring. 
Unless, with a small probability, mutation changes the allelic value of the offspring.
After birth individuals go through a round of viavility selection. 
Individual specific survival probability is given by $s_i=1/(1+e^{-k_1-k_2(Q_i-B_i)}$. 
Where $k_1$ and $k_2$ are parameter values determining the shape of the survival function. 
Importantly, if $k_2=0$ survival probability is independent of quality, while if $k_2>0$
lower quality individuals pay a higher price for s similar-sized badge, fulfilling the core assumption 
of the handicap principle [@botero_Evolution_2010; @grafen_Biological_1990; @johnstone_Badges_1993].

Individuals who survive engage in a series of pairwise interactions 
where they compete for resources. Individuals in real populations typically do not 
interact at random nor with all individuals in the population [@kurvers_Evolutionary_2014]. 
In order to allow for non-random interactions, we use the population vector to define 
an interaction neighborhood for the focal individual, the size of the neighborhood (g) 
is the number of positions around the focal´s from which the interactant is drawn. 
So, if $g=N$ interactions are global; as $g$ gets smaller interactions are more local. 
In an interaction each individual must decide whether to escalate a fight or not. 
Following the classic hawk-dove game [@maynard-smith_Evolution_1982], if the focal individual fights and its partner does not, the focal gets as payoff the resource of value $V$ while its partner gets nothing; if both individuals restrain  from fighting they split up the resource in half; if both decide to fight they splitup the cost of fighting and the winner takes over the resource. 
We further assume that the probability of wining a fight for the focal individual depends on the difference in quality between her and her interacting partner; specifically it is given by $p_{ij}=1/(1+e^{-k_3(Q_i-Q_j)})$, where $k_3$ is a parameter defining
how strong the quality difference determines the winning probability; 
and $i$ and $j$ denote the the position in the population 
vector of the focal and its interacting partner respectively.

The decision of whether to escalate a fight against an interacting partner can be dependent 
on the size of the partner´s badge, the actual dependency is determined by 
the focal´s experiences through a learning process. We implement learning using 
the actor-critic aproach from reinforcement learning theory [RL; @sutton_Reinforcement_2018;@quinones_Reinforcement_2019; @leimar_Learning_2019].
Individuals estimate the reward (payoff) expected from  interacting with partners 
of different badge sizes (the critic in RL terminology). 
After every interaction they update the estimate of reward proportionally to the difference between their current estimate and the observed reward (prediction error $\delta$). Furthermore, they express different probabilities of escalatining (retreating) depending on
the badge size of their opponent (the actor in RL). They update the probability of 
retreating (escalating)  up or down depending on whether retreating (escalating) leads to an increase 
in the reward estimation. So, if a focal individual decides to escalate a fight against 
an individual with small badge, and that leads to an increase in the reward estimation,
the focal individual will increase the probability of escalating fights with 
individuals of small badges in the future. Given that badge size is a real number between 0 and 1,
the reward estimation, as well as the probability of retreating (escalating), must be
generalized across different values. To implement generalization we use the function
approximation method based on radial basis functions [@sutton_Reinforcement_2018]. Specifically, we pick $c$ evenly spaced 
values along the badge size interval, 





## References